/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Rumah() {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Home/Rumah-transformed.glb");
  return (
    <group ref={group} dispose={null}>
      <group position={[0.19, 0.86, 0.19]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube_1.geometry} material={materials.Material} />
        <mesh castShadow receiveShadow geometry={nodes.Cube_2.geometry} material={nodes.Cube_2.material} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Plane.geometry} material={nodes.Plane.material} scale={5.65} />
      <mesh castShadow receiveShadow geometry={nodes.Icosphere.geometry} material={nodes.Icosphere.material} position={[-3.48, 1.63, -0.46]} scale={0.3} />
      <mesh castShadow receiveShadow geometry={nodes.Icosphere001.geometry} material={nodes.Icosphere001.material} position={[-3.73, 1.35, -0.44]} scale={0.39} />
      <mesh castShadow receiveShadow geometry={nodes.Icosphere002.geometry} material={nodes.Icosphere002.material} position={[-3.26, 1.45, -0.32]} scale={0.33} />
      <mesh castShadow receiveShadow geometry={nodes.Silinder.geometry} material={nodes.Silinder.material} position={[-3.46, 0.65, -0.42]} scale={[0.11, 0.7, 0.11]} />
    </group>
  );
}

useGLTF.preload("/Home/Rumah-transformed.glb");
